name: code-quality-actions

on: [push]

env:
  PYTHON-VERSION: 3.8

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python $PYTHON-VERSION
        uses: actions/setup-python@v3
        with:
          python-version: $PYTHON-VERSION
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Analysing the code with black
        run: black --check .
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python $PYTHON-VERSION
        uses: actions/setup-python@v3
        with:
          python-version: $PYTHON-VERSION
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install isort
      - name: Analysing the code with isort
        run: isort --check .
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python $PYTHON-VERSION
        uses: actions/setup-python@v3
        with:
          python-version: $PYTHON-VERSION
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Analysing the code with flake8
        run: flake8 nlp_transformers
